// <auto-generated />
using System;
using BigBang1112.GbxTools.Titles.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BigBang1112.GbxTools.Titles.BlazorWebApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260210150537_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BigBang1112.GbxTools.Titles.Entities.HistoricalPlayerCountEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OnlinePlayers")
                        .HasColumnType("int");

                    b.Property<int>("PlayersLast24h")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Registrations")
                        .HasColumnType("int");

                    b.Property<string>("TitleId")
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("TitleId");

                    b.ToTable("HistoricalPlayerCounts");
                });

            modelBuilder.Entity("BigBang1112.GbxTools.Titles.Entities.TitleEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("AuthorLogin")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("AuthorNickname")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("BackgroundUrl")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("CardUrl")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeformattedName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<string>("DownloadUrl")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("FacebookUrl")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ForumUrl")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<bool>("IsEnvironment")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsMatchmaking")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsMultiplayer")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsShootmania")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsSolo")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsTrackmania")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset>("LastUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<int>("OnlinePlayers")
                        .HasColumnType("int");

                    b.Property<int>("PlayersLast24h")
                        .HasColumnType("int");

                    b.Property<string>("PrimaryColor")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.Property<string>("Punchline")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Registrations")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StoredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TitleMakerName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("TitleMakerUid")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("TitlePageUrl")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("TwitterUrl")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("YoutubeUrl")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id");

                    b.ToTable("Titles");
                });

            modelBuilder.Entity("BigBang1112.GbxTools.Titles.Entities.TitleFileEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Checksum")
                        .HasMaxLength(16)
                        .HasColumnType("varbinary(16)");

                    b.Property<uint>("ClassId")
                        .HasColumnType("int unsigned");

                    b.Property<int>("CompressedSize")
                        .HasColumnType("int");

                    b.Property<ulong>("Flags")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("FolderPath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<uint>("Offset")
                        .HasColumnType("int unsigned");

                    b.Property<int?>("Size")
                        .HasColumnType("int");

                    b.Property<int>("TitleMetadataId")
                        .HasColumnType("int");

                    b.Property<int>("UncompressedSize")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TitleMetadataId");

                    b.ToTable("TitleFiles");
                });

            modelBuilder.Entity("BigBang1112.GbxTools.Titles.Entities.TitleIncludedPackEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorExtraInfo")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("AuthorLogin")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("AuthorNickname")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("AuthorVersion")
                        .HasColumnType("int");

                    b.Property<string>("AuthorZone")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<byte[]>("ContentsChecksum")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varbinary(32)");

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<uint>("IncludeDepth")
                        .HasColumnType("int unsigned");

                    b.Property<string>("InfoManialinkUrl")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("TitleMetadataId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TitleMetadataId");

                    b.ToTable("TitleIncludedPacks");
                });

            modelBuilder.Entity("BigBang1112.GbxTools.Titles.Entities.TitleMetadataEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorExtraInfo")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("AuthorLogin")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("AuthorNickname")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("AuthorUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("AuthorVersion")
                        .HasColumnType("int");

                    b.Property<string>("AuthorZone")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<byte[]>("Checksum")
                        .HasMaxLength(32)
                        .HasColumnType("varbinary(32)");

                    b.Property<string>("Comments")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<long?>("ContentLength")
                        .HasColumnType("bigint");

                    b.Property<string>("CreationBuildInfo")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTimeOffset?>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DownloadUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ETag")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<uint>("Flags")
                        .HasColumnType("int unsigned");

                    b.Property<int?>("GbxHeadersComprSize")
                        .HasColumnType("int");

                    b.Property<int?>("GbxHeadersSize")
                        .HasColumnType("int");

                    b.Property<uint>("GbxHeadersStart")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("HeaderFlags")
                        .HasColumnType("int unsigned");

                    b.Property<byte[]>("HeaderMD5")
                        .HasMaxLength(16)
                        .HasColumnType("varbinary(16)");

                    b.Property<int?>("HeaderMaxSize")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("LastUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ManialinkUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<uint?>("Size")
                        .HasColumnType("int unsigned");

                    b.Property<DateTimeOffset>("StoredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TitleId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<byte[]>("U01")
                        .HasMaxLength(16)
                        .HasColumnType("varbinary(16)");

                    b.Property<string>("UsageSubDir")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<string>("Xml")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.HasKey("Id");

                    b.HasIndex("TitleId");

                    b.ToTable("TitleMetadata");
                });

            modelBuilder.Entity("BigBang1112.GbxTools.Titles.Entities.TitleScriptEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("MatchSettings")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TitleId")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("TitleId");

                    b.ToTable("TitleScripts");
                });

            modelBuilder.Entity("BigBang1112.GbxTools.Titles.Entities.HistoricalPlayerCountEntity", b =>
                {
                    b.HasOne("BigBang1112.GbxTools.Titles.Entities.TitleEntity", "Title")
                        .WithMany()
                        .HasForeignKey("TitleId");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("BigBang1112.GbxTools.Titles.Entities.TitleFileEntity", b =>
                {
                    b.HasOne("BigBang1112.GbxTools.Titles.Entities.TitleMetadataEntity", "TitleMetadata")
                        .WithMany("Files")
                        .HasForeignKey("TitleMetadataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TitleMetadata");
                });

            modelBuilder.Entity("BigBang1112.GbxTools.Titles.Entities.TitleIncludedPackEntity", b =>
                {
                    b.HasOne("BigBang1112.GbxTools.Titles.Entities.TitleMetadataEntity", "TitleMetadata")
                        .WithMany()
                        .HasForeignKey("TitleMetadataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TitleMetadata");
                });

            modelBuilder.Entity("BigBang1112.GbxTools.Titles.Entities.TitleMetadataEntity", b =>
                {
                    b.HasOne("BigBang1112.GbxTools.Titles.Entities.TitleEntity", "Title")
                        .WithMany()
                        .HasForeignKey("TitleId");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("BigBang1112.GbxTools.Titles.Entities.TitleScriptEntity", b =>
                {
                    b.HasOne("BigBang1112.GbxTools.Titles.Entities.TitleEntity", "Title")
                        .WithMany()
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Title");
                });

            modelBuilder.Entity("BigBang1112.GbxTools.Titles.Entities.TitleMetadataEntity", b =>
                {
                    b.Navigation("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
